// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Job struct {
	ID              int64     `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	Company         string    `json:"company"`
	Location        string    `json:"location"`
	MinSalary       string    `json:"min_salary"`
	MaxSalary       string    `json:"max_salary"`
	Type            string    `json:"type"`
	ExperienceLevel string    `json:"experience_level"`
	Skills          string    `json:"skills"`
	UserID          int32     `json:"user_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	Role           string         `json:"role"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
